added support for troubleshooting

diff --git a/install-lsyncd b/install-lsyncd
--- a/install-lsyncd
+++ b/install-lsyncd
@@ -11,7 +11,7 @@ lc() { echo "$1" | perl -ne 'print lc'; }
 is_in() { local i= a="$1"; shift; for i; do [ "$a" = "$i" ] && return 0; done; return 1; }
 in_path() { echo "$PATH" | awk -F: -v d="$(dirname "$1")" '{for(i=1;i<=NF;i++)if(d==$i){c=1;break}}END{exit!c}'; }
 is_int() { echo "$1" | awk '$0+0!=$0{exit(1)}'; }
-debug() { echo '#' "$@" >&2; "$@"; }
+debug() { echo -e '\x1b[33m#' "$@" '\x1b[0m' >&2; "$@"; }
 help() {
     in_path "$0" && APP="$(basename "$0")" || APP="$0"
     echo
@@ -137,9 +137,14 @@ TEMP="$(mktemp -t lsyncd-known_hosts-XXXX)"
 echo "INFO: Created tempfile=$TEMP"
 trap "{ rm -f '$TEMP' && echo 'INFO: Removed tempfile=$TEMP'; }" EXIT
 
-[ "$(docker run --rm "$@" \
-    -v "$TEMP:/root/.ssh/known_hosts" \
-    solargis/lsyncd echo ok)" != "ok" ] && fail "Unable to connect."
+if ! docker run --rm "$@" -v "$TEMP:/root/.ssh/known_hosts" solargis/lsyncd true; then
+    rm "$TEMP" && trap - EXIT && echo "INFO: Removed tempfile=$TEMP"
+    fail "Unable to connect."
+    echo "Do you want inspect command 'ssh $TARGET_HOST' inside container?"
+    read -p "[yN]> "
+    [ "$(lc "$REPLY")" = y ] && debug docker run --rm "$@" -it solargis/lsyncd bash
+    exit 1
+fi
 
 HOST_KEY="$(awk '{print $2" "$3}' "$TEMP")"
 rm "$TEMP" && trap - EXIT && echo "INFO: Removed tempfile=$TEMP"
